server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.1.111.135:1521:MEDB
      username: springboot
      password: 123456
  jpa:
    show-sql: true
      
logging:
  level:
     com.fhzz.psopadmin.dao : debug