server:
  port: 8762
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.2.212.245:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
      name: psop-admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.2.212.245:1521:MEDB
      username: PSOP
      password: 123456
      logSlowSql: true
  jpa:
    show-sql: true
      
logging:
  level:
     com.fhzz.psopadmin.dao : debug
     