server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: psop-web
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.2.108.238:1521:ORCL
    username: C##PSOPUSER
    password: 123456