eureka:
  client:
    serviceUrl:
      defaultZone: http://10.2.212.245:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: psop-zuul
zuul:
  routes:
    psop-admin:
      path: /admin/**
      serviceId: psop-admin
    psop-index:
      path: /index/**
      serviceId: psop-index
